### ISSUE TITLE
1.13.2

### ISSUE THREAD

**Issue by WhitePaper233** [TISUnion/PCRC-MCDR#1]
It is said that PCRC hasn't supported minecraft 1.13.2 yet,so how did u guys use PCRC on 1.13.2 server?

**Comment by Fallen-Breath** [comment]
we use viaversion plugin on bungeecord. it allow client in almost any version to connect to server in almost any version

**Comment by WhitePaper233** [comment]
> we use viaversion plugin on bungeecord. it allow client in almost any version to connect to server in almost any version

By using bungeecord,so is this how you jump between survival, creative and mirror server?

**Comment by Fallen-Breath** [comment]
yep

**Comment by WhitePaper233** [comment]
> yep

OK.Thanks a lot!
