### ISSUE TITLE
PCRC的使用

### ISSUE THREAD

**Issue by DancingSnow0517** [TISUnion/PCRC-MCDR#2]
能不能把PCRC的start和stop加入游戏中使用？加个权限，例如admin才能使用

**Comment by Fallen-Breath** [comment]
这个插件就是提供一个!!PCRC start的功能，加权限控制倒不难。不过其余指令是通过PCRC客户端自己实现的，没进过mcd，因此可能做不了权限相关

**Comment by DancingSnow0517** [comment]
哦，我明白了
